### ISSUE TITLE
Configuration file does not contain valid YAML

### ISSUE THREAD

**Issue by SergeyPodgornyy** [sitemap-php/KPhoenSitemapBundle#8]
## Detailed description

While generating sitemap using console command `php bin/console sitemap:generate` I am receiving an error, that configuration `.yml`-files are invalid

![yaml](https://user-images.githubusercontent.com/13667212/33150973-3ec1ca32-cfd6-11e7-88c5-e898f77babe3.png)

## Context

I am planning to use your library to generate sitemap, but right now I can't do this, because of invalid YAML.

## Possible implementation

All we need to do is wrap parameters, which starts with `@` as a string, with quotes:

```yml
    sitemap:
        class:      SitemapGenerator\Sitemap\Sitemap
        arguments:  [ "@sitemap_gz_dumper", "@sitemap_xml_formatter", "%sitemap.config.base_host%", "%sitemap.config.base_host_sitemap%", "%sitemap.config.limit%" ]
```

## Environment

- PHP version 7.1
- Operating system Ubuntu 16.04
- Symfony 3.3.13
