### ISSUE TITLE
Add support Symfony 3.* and since November 30th 2017, also Symfony 4.*

### ISSUE THREAD

**Issue by SergeyPodgornyy** [sitemap-php/KPhoenSitemapBundle#9]
## Detailed description

Create new MAJOR release to support Symfony 3.* and since November 30th 2017, also Symfony 4.*

## Context

Symfony 3.0.0 has been released at November 30, 2015. This is already 2 years old, and modern projects trying to follow modern techniques, that why important to add support also for newer versions.

## Possible implementation

As far as I discovered this Bundle, at least `routing.yml` should be changed:

```yml
sitemap:
  path: /sitemap.xml
  defaults: { _controller: KPhoenSitemapBundle:Sitemap:sitemap }
  methods: [GET]
```

## Your environment

* PHP version 7.1
* Operating system Ubuntu 16.04
* Symfony version 3.3.13
